module.exports = {
    'Spawn1': {
        room: 'W14N37',
        min: {
            harvester: 2,
            builder: 1,
            upgrader: 1,
            transporter: 4,
            transfer: 3,
            claimer: 0,
            pioneer: 0,
            harasser: 0,
            scout: 0,
            defender: 0,
            medic: 0,
            collector: 1,
            extractor: 1,
            labManager: 0,
        },
        bodies: {
            harvester: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            builder: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            upgrader: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            transporter: [WORK,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            transfer: [CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            defender: [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,RANGED_ATTACK,RANGED_ATTACK,MOVE,MOVE,MOVE,MOVE,MOVE],
            harasser: [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,MOVE,MOVE,MOVE,HEAL,MOVE,MOVE,MOVE,MOVE],
            medic: [HEAL,MOVE,MOVE],
            claimer: [CLAIM,MOVE],
            pioneer: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            scout: [MOVE],
            collector: [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,],
            extractor: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            labManager: [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
        },
        memory: {
            harvester: { group: 1 },
            builder: { group: 1 },
            upgrader: { group: 1 },
            transporter: { group: 3 },
            transfer: { group: 1 },
            harasser: { targetRoom: 'W14N37' },
            medic: { targetRoom: 'W14N37', follow: 'MedicBuddy' },
            claimer: { targetRoom: 'W13N33', suicideAfterClaim: false },
            pioneer: { targetRoom: 'W13N33', group: 1 },
            scout: { group: 1 },
            collector: { group: 1 },
            extractor: {},
            labManager: { group: 1 },
        }
    },
    
    'Spawn2': {
        room: 'W15N37',
        min: {
            harvester: 2,
            builder: 0,
            upgrader: 1,
            transporter: 4,
            transfer: 2,
            claimer: 0,
            pioneer: 0,
            harasser: 0,
            scout: 0,
            defender: 0,
            medic: 0,
            collector: 1,
            extractor: 1,
            labManager: 0,
        },
        bodies: {
            harvester: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            builder: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            upgrader: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            transporter: [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            transfer: [CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE],
            defender: [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,RANGED_ATTACK,RANGED_ATTACK,MOVE,MOVE,MOVE,MOVE,MOVE],
            harasser: [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,MOVE,MOVE,MOVE,HEAL,MOVE,MOVE,MOVE,MOVE],
            medic: [HEAL,MOVE,MOVE],
            claimer: [CLAIM,MOVE],
            pioneer: [WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
            scout: [MOVE],
            collector: [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            extractor: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            labManager: [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
        },
        memory: {
            harvester: { group: 2 },
            builder: { group: 2 },
            upgrader: { group: 1 },
            transporter: { group: 3 },
            transfer: { group: 3 },
            harasser: { targetRoom: 'W14N37' },
            medic: { targetRoom: 'W14N37', follow: 'MedicBuddy' },
            claimer: { targetRoom: 'W15N37', suicideAfterClaim: false },
            pioneer: { targetRoom: 'W15N37', group: 1 },
            scout: { group: 2 },
            collector:{ group: 1 },
            extractor: {},
            labManager: { group: 1 },
        }
    },
    'Spawn3': {
        room: 'W13N39',
        min: {
            harvester: 2,
            builder: 0,
            upgrader: 1,
            transporter: 4,
            transfer: 2,
            claimer: 0,
            pioneer: 0,
            harasser: 0,
            scout: 0,
            defender: 0,
            medic: 0,
            collector: 1,
            extractor: 1,
            labManager: 0,
        },
        bodies: {
            harvester: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            builder: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            upgrader: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            transporter: [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            transfer: [CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE],
            defender: [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,RANGED_ATTACK,RANGED_ATTACK,MOVE,MOVE,MOVE,MOVE,MOVE],
            harasser: [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,MOVE,MOVE,MOVE,HEAL,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            medic: [HEAL,MOVE,MOVE],
            claimer: [CLAIM,MOVE],
            pioneer: [WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
            scout: [MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            collector: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            // groups 1-3 CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE
            // group 4 collector WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE
            extractor: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            labManager: [CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE],
        },
        memory: {
            harvester: { group: 2 },
            builder: { group: 2 },
            upgrader: { group: 1 },
            transporter: { group: 2 },
            transfer: { group: 3 },
            harasser: { targetRoom: 'W12N40' },
            medic: { targetRoom: 'W14N37', follow: 'MedicBuddy' },
            claimer: { targetRoom: 'W15N37', suicideAfterClaim: false },
            pioneer: { targetRoom: 'W15N37', group: 1 },
            scout: { group: 2 },
            collector:{ group: 4 },
            extractor: {},
            labManager: { group: 1 },
        }
    },
    'Spawn4': {
        room: 'W15N37',
        min: {
            harvester: 0,
            builder: 0,
            upgrader: 0,
            transporter: 0,
            transfer: 0,
            claimer: 0,
            pioneer: 0,
            harasser: 0,
            scout: 0,
            defender: 0,
            medic: 0,
            collector: 0,
            extractor: 0,
            labManager: 0,
        },
        bodies: {
            harvester: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            builder: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            upgrader: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            transporter: [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            transfer: [CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE],
            defender: [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,RANGED_ATTACK,RANGED_ATTACK,MOVE,MOVE,MOVE,MOVE,MOVE],
            harasser: [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,MOVE,MOVE,MOVE,HEAL,MOVE,MOVE,MOVE,MOVE],
            medic: [HEAL,MOVE,MOVE],
            claimer: [CLAIM,MOVE],
            pioneer: [WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
            scout: [MOVE],
            collector: [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            extractor: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            labManager: [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
        },
        memory: {
            harvester: { group: 2 },
            builder: { group: 2 },
            upgrader: { group: 1 },
            transporter: { group: 3 },
            transfer: { group: 3 },
            harasser: { targetRoom: 'W14N37' },
            medic: { targetRoom: 'W14N37', follow: 'MedicBuddy' },
            claimer: { targetRoom: 'W15N37', suicideAfterClaim: false },
            pioneer: { targetRoom: 'W15N37', group: 1 },
            scout: { group: 2 },
            collector:{ group: 1 },
            extractor: {},
            labManager: { group: 1 },
        }
    },
    'Spawn5': {
        room: 'W13N33',
        min: {
            harvester: 0,
            builder: 0,
            upgrader: 0,
            transporter: 0,
            transfer: 0,
            claimer: 0,
            pioneer: 0,
            harasser: 0,
            scout: 0,
            defender: 0,
            medic: 0,
            collector: 0,
            extractor: 0,
            labManager: 0,
        },
        bodies: {
            harvester: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            builder: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            upgrader: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            transporter: [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            transfer: [CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE],
            defender: [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,RANGED_ATTACK,RANGED_ATTACK,MOVE,MOVE,MOVE,MOVE,MOVE],
            harasser: [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,MOVE,MOVE,MOVE,HEAL,MOVE,MOVE,MOVE,MOVE],
            medic: [HEAL,MOVE,MOVE],
            claimer: [CLAIM,MOVE],
            pioneer: [WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
            scout: [MOVE],
            collector: [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            extractor: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            labManager: [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
        },
        memory: {
            harvester: { group: 2 },
            builder: { group: 2 },
            upgrader: { group: 1 },
            transporter: { group: 3 },
            transfer: { group: 3 },
            harasser: { targetRoom: 'W14N37' },
            medic: { targetRoom: 'W14N37', follow: 'MedicBuddy' },
            claimer: { targetRoom: 'W15N37', suicideAfterClaim: false },
            pioneer: { targetRoom: 'W15N37', group: 1 },
            scout: { group: 2 },
            collector:{ group: 1 },
            extractor: {},
            labManager: { group: 1 },
        }
    },
    'Spawn6': {
        room: 'W14N37',
        min: {
            harvester: 0,
            builder: 0,
            upgrader: 0,
            transporter: 0,
            transfer: 0,
            claimer: 0,
            pioneer: 0,
            harasser: 0,
            scout: 0,
            defender: 0,
            medic: 0,
            collector: 0,
            extractor: 0,
            labManager: 0,
        },
        bodies: {
            harvester: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            builder: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            upgrader: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            transporter: [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            transfer: [CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE],
            defender: [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,RANGED_ATTACK,RANGED_ATTACK,MOVE,MOVE,MOVE,MOVE,MOVE],
            harasser: [TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,TOUGH,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,RANGED_ATTACK,MOVE,MOVE,MOVE,HEAL,MOVE,MOVE,MOVE,MOVE],
            medic: [HEAL,MOVE,MOVE],
            claimer: [CLAIM,MOVE],
            pioneer: [WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE],
            scout: [MOVE],
            collector: [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            extractor: [WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,WORK,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
            labManager: [CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,CARRY,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE,MOVE],
        },
        memory: {
            harvester: { group: 2 },
            builder: { group: 2 },
            upgrader: { group: 1 },
            transporter: { group: 3 },
            transfer: { group: 3 },
            harasser: { targetRoom: 'W14N37' },
            medic: { targetRoom: 'W14N37', follow: 'MedicBuddy' },
            claimer: { targetRoom: 'W15N37', suicideAfterClaim: false },
            pioneer: { targetRoom: 'W15N37', group: 1 },
            scout: { group: 2 },
            collector:{ group: 1 },
            extractor: {},
            labManager: { group: 1 },
        }
    },
};